# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
  #   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
  #   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
    GMAIL_DOMAIN: "gmail.com"
    GMAIL_USERNAME: "gauthier.fraiture@gmail.com"
    GMAIL_PASSWORD: "akerprepa13"
    FACEBOOK_KEY: "1053226671422283"
    FACEBOOK_SECRET: "82aa83ccefd715b47da23c1a25ee37c9"
    LINKEDIN_KEY: "77rq5jgmj9jqq7"
    LINKEDIN_SECRET: "NIoTu8oksZ2XiEZk"

production:
     FACEBOOK_KEY: "1053216601423290"
     FACEBOOK_SECRET: "a4767391dbf4907663dbfd6cfebcb7f4"
     LINKEDIN_KEY: "77rq5jgmj9jqq7"
     LINKEDIN_SECRET: "NIoTu8oksZ2XiEZk"
